### ISSUE TITLE
center embedded google doc?

### ISSUE THREAD

**Issue by jovo** [neurodata/brainx#1]
@ronnyb29 i can't figure out how to center the embedded google doc.
if you can pull request to fix it, that'd be cool.
obviously, i know, not a huge top priority for you.

**Comment by ronboger** [comment]
@jovo what file? i'll check it out

**Comment by jovo** [comment]
@ronnyb29 not sure "what file?" means.
this: https://github.com/neurodata/brainx/blob/gh-pages/index.html
?
